spring:
  application:
    name: spring-kafka-con
  kafka:
    consumer:
      bootstrap-servers: localhost:9092
      group-id: kafka1SpringGroup, kafka2SpringGroup
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: '*'
        spring.json.type.mapping: dataDemoDto:com.pxc.spring_kafka_con.kafka.DataDemoDto, elementDemoDto:com.pxc.spring_kafka_con.kafka.ElementDemoDto
server:
  port: 7080