spring:
  application:
    name: spring-kafka-con
  kafka:
    consumer:
      bootstrap-servers: localhost:9092
      group-id: kafkaSpringGroup
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      properties:
        spring.json.trusted.packages: '*'
        spring.deserializer.value.delegate.class: org.springframework.kafka.support.serializer.JsonDeserializer
        spring.json.value.default.type: com.pxc.spring_kafka_con.kafka.DataDemoDto
server:
  port: 7080